//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGimnasiaYEsgrima.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuotaSocio
    {
        public int IdCuota { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaCobro { get; set; }
        public double Importe { get; set; }
        public EnumEstadoCuotaSocio Estado { get; set; }
    
        public virtual ValorCuotaInicial ValorCuotaInicial { get; set; }
        public virtual Socio Socio { get; set; }
    }
}
