//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGimnasiaYEsgrima.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiagramasDeTablasContainer1 : DbContext
    {
        public DiagramasDeTablasContainer1()
            : base("name=DiagramasDeTablasContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<Deporte> Deportes { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
    }
}
