//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGimnasiaYEsgrima.Modelo
{
    using System;
    
    public enum EnumEstadoCurso : int
    {
        Inicial = 1,
        Pendiente = 2,
        Activo = 3,
        Finalizado = 4,
        Anulado = 5
    }
}
